[package]
name = "coolvs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version="3.1", features=["derive"] }
colored = "2.0.0"
keyring = "2.0.5"
rpassword = "7.2.0"
chacha20poly1305 = "0.10.1"
sled = "0.34.7"
dirs = "5.0.1"
argon2 = "0.5.1"
crypto-common = "0.1.6"
sha2 = "0.10.7"

